### PR TITLE
Remove Datapoint plugin resource

### PR DESCRIPTION
**Pull request by shashiranjan84**
# Related issue:
- https://transcend.height.app/T-21568

### CODE REVIEW

**Review by dipack95 — COMMENTED** [review]
You also need to update the [version](https://github.com/transcend-io/terraform-provider-transcend/blob/cb74b82695775e5bd74cb056012cd235f5999fd6/Makefile#L6)!

**Comment by shashiranjan84** [comment]
@dipack95 @dipack95 how to make test pass? like here they seems like looking for new version.

**Comment by shashiranjan84** [comment]
> @dipack95 @dmattia how to make test pass? like here they seems like looking for new version.

I think I was required to update version everywhere

**Review by dipack95 — APPROVED** [review]
Looks good to me

**Comment by shashiranjan84** [comment]
@dipack95 any idea why this failing https://github.com/transcend-io/terraform-provider-transcend/actions/runs/4001384213/jobs/6867564712#step:7:240? I see values here passed in as array not string. Also not sure how its related to my changes..

**Comment by dipack95** [comment]
@shashiranjan84 I can't find anything obvious, but I would debug what's happening in the `options` var [here](https://github.com/transcend-io/terraform-provider-transcend/blob/main/transcend/resource_data_point_test.go#L461).

**Comment by shashiranjan84** [comment]
> @dipack95 any idea why this failing https://github.com/transcend-io/terraform-provider-transcend/actions/runs/4001384213/jobs/6867564712#step:7:240? I see values here passed in as array not string. Also not sure how its related to my changes..

Its not failing because of my change for sure as it is failing on main branch too https://github.com/transcend-io/terraform-provider-transcend/actions/runs/4010107879/jobs/6886243189#step:7:246. May be something changed on backend for datapoint attributes which causing this issue.

**Comment by shashiranjan84** [comment]
I am merging this and look for failing test separately

**Pull request merged**
